name: Auto Image Resize

on:
  push:
    paths:
      - 'assets/**'  # assets 폴더에 파일이 추가될 때만 작동

jobs:
  resize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick
      - name: Resize Images
              run: |
            # 600을 200으로 변경.
            # '>' 기호를 빼면 기존에 600이었던 것들도 강제로 200으로 다시 줄입니다.
              find assets/ -type f \( -name "*.jpg" -o -name "*.jpeg" -o -name "*.png" \) -exec mogrify -resize '200' {} +
      - name: Commit and Push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/
          git commit -m "chore: auto resize images to 600px" || echo "No changes to commit"
          git push
